


Set up environment
```{r}
rm(list = ls())
set.seed(123)
```

## Part 2 - Extrapolation
Since there are multiple data fields that will be a significant component of this analysis, we will need to make some assumptions about missing data We can later choose to use this data or not, however we can at least make it available.
```{r}
packageload <- c("tidyverse","kableExtra","plotly","lubridate","zoo","urca","base","caTools","caret","priceR","countrycode","plyr","data.table","utilsIPEA","Hmisc")
pacman::p_load(char = packageload)
```

## Method 1 - Use Approx Extrapolation
```{r}
require(utils)
data_new <- fread("C:\\Users\\Jonathan\\Documents\\R\\Netflix\\Merged_Dataset_2.csv", select=c("IMDb_Score","Rotten_Tomatoes_Score"))
data_new <- data.frame(data_new)
data_new$IMDb_Score<-as.integer(data_new$IMDb_Score)
#sort the data by IMDb Score
data<- data_new[order(data_new$IMDb_Score),]
data_new[] <- sapply(data_new, function(y) {
      xs <- seq_along(y)
      Hmisc::approxExtrap(x = xs[!is.na(y)], y = y[!is.na(y)], xout = xs)$y
    })
kable(data_new[1:2]) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  scroll_box(width = "100%", height = "500px")
```

## Method 2 - Create a linear regression prediction
```{r}
data_new <- fread("C:\\Users\\Jonathan\\Documents\\R\\Netflix\\Merged_Dataset_2.csv", select=c("Title","IMDb_Score","Rotten_Tomatoes_Score"))
data_new <- data.frame(data_new)
predictions <- round(predict(lm(Rotten_Tomatoes_Score ~ IMDb_Score, data_new), newdata = data_new), 2)
data_new$Rotten_Tomatoes_Score_Ext<-data_new$Rotten_Tomatoes_Score
data_new$Rotten_Tomatoes_Score_Ext[is.na(data_new$Rotten_Tomatoes_Score_Ext)] <- predictions[is.na(data_new$Rotten_Tomatoes_Score)]
kable(data_new[1:4]) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  scroll_box(width = "100%", height = "500px")
```
```

```

